"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.service = exports.Service = exports.PUT = exports.provider = exports.Provider = exports.POST = exports.module = exports.Module = exports.middleware = exports.Middleware = exports.GET = exports.DELETE = exports.controller = exports.Controller = exports.Base = exports.application = exports.Application = void 0;
const src_1 = require("./src");
Object.defineProperty(exports, "Application", { enumerable: true, get: function () { return src_1.Application; } });
Object.defineProperty(exports, "application", { enumerable: true, get: function () { return src_1.application; } });
Object.defineProperty(exports, "Base", { enumerable: true, get: function () { return src_1.Base; } });
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return src_1.Controller; } });
Object.defineProperty(exports, "controller", { enumerable: true, get: function () { return src_1.controller; } });
Object.defineProperty(exports, "DELETE", { enumerable: true, get: function () { return src_1.DELETE; } });
Object.defineProperty(exports, "GET", { enumerable: true, get: function () { return src_1.GET; } });
Object.defineProperty(exports, "Middleware", { enumerable: true, get: function () { return src_1.Middleware; } });
Object.defineProperty(exports, "middleware", { enumerable: true, get: function () { return src_1.middleware; } });
Object.defineProperty(exports, "Module", { enumerable: true, get: function () { return src_1.Module; } });
Object.defineProperty(exports, "module", { enumerable: true, get: function () { return src_1.module; } });
Object.defineProperty(exports, "POST", { enumerable: true, get: function () { return src_1.POST; } });
Object.defineProperty(exports, "Provider", { enumerable: true, get: function () { return src_1.Provider; } });
Object.defineProperty(exports, "provider", { enumerable: true, get: function () { return src_1.provider; } });
Object.defineProperty(exports, "PUT", { enumerable: true, get: function () { return src_1.PUT; } });
Object.defineProperty(exports, "Service", { enumerable: true, get: function () { return src_1.Service; } });
Object.defineProperty(exports, "service", { enumerable: true, get: function () { return src_1.service; } });
//# sourceMappingURL=index.js.map