"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AOPMiddleware = exports.Base = exports.AOPController = exports.AOPProvider = exports.AOPModule = exports.AOPService = exports.AOPApplication = exports.DELETE = exports.Provider = exports.POST = exports.PUT = exports.GET = exports.Module = exports.Middleware = exports.Controller = exports.Application = exports.Service = void 0;
const annotation_1 = require("./annotation");
Object.defineProperty(exports, "Application", { enumerable: true, get: function () { return annotation_1.Application; } });
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return annotation_1.Controller; } });
Object.defineProperty(exports, "DELETE", { enumerable: true, get: function () { return annotation_1.DELETE; } });
Object.defineProperty(exports, "GET", { enumerable: true, get: function () { return annotation_1.GET; } });
Object.defineProperty(exports, "Middleware", { enumerable: true, get: function () { return annotation_1.Middleware; } });
Object.defineProperty(exports, "Module", { enumerable: true, get: function () { return annotation_1.Module; } });
Object.defineProperty(exports, "POST", { enumerable: true, get: function () { return annotation_1.POST; } });
Object.defineProperty(exports, "Provider", { enumerable: true, get: function () { return annotation_1.Provider; } });
Object.defineProperty(exports, "PUT", { enumerable: true, get: function () { return annotation_1.PUT; } });
Object.defineProperty(exports, "Service", { enumerable: true, get: function () { return annotation_1.Service; } });
const declarations_1 = require("./declarations");
Object.defineProperty(exports, "AOPApplication", { enumerable: true, get: function () { return declarations_1.AOPApplication; } });
Object.defineProperty(exports, "AOPController", { enumerable: true, get: function () { return declarations_1.AOPController; } });
Object.defineProperty(exports, "AOPMiddleware", { enumerable: true, get: function () { return declarations_1.AOPMiddleware; } });
Object.defineProperty(exports, "AOPModule", { enumerable: true, get: function () { return declarations_1.AOPModule; } });
Object.defineProperty(exports, "AOPProvider", { enumerable: true, get: function () { return declarations_1.AOPProvider; } });
Object.defineProperty(exports, "AOPService", { enumerable: true, get: function () { return declarations_1.AOPService; } });
Object.defineProperty(exports, "Base", { enumerable: true, get: function () { return declarations_1.Base; } });
//# sourceMappingURL=index.js.map